name: Deploy to Production

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git pull origin prod
            composer install --no-dev --prefer-dist --optimize-autoloader
